services:
  react-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: always
    networks:
      IPStatic:
        ipv4_address: 172.0.0.3

# Definisi network jika dibutuhkan
networks:
  IPStatic:
    external: true
    ipam:
      driver: default
      config:
        - subnet: "172.0.0.0/24"
